# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: match.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='match.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('Z\037github.com/ajzaff/bot_zoo/proto'),
  serialized_pb=_b('\n\x0bmatch.proto\"\xcc\x02\n\x03PGN\x12\x13\n\x0bgold_player\x18\x01 \x01(\t\x12\x15\n\rsilver_player\x18\x02 \x01(\t\x12\x0b\n\x03pgn\x18\x07 \x01(\t\x12\x11\n\x05steps\x18\x03 \x03(\rB\x02\x10\x01\x12$\n\x0b\x61nnotations\x18\x05 \x03(\x0b\x32\x0f.PGN.Annotation\x12\x0e\n\x06result\x18\x06 \x01(\x05\x1a\x87\x01\n\nAnnotation\x12\x0c\n\x04step\x18\x02 \x01(\t\x12\x0f\n\x07\x63omment\x18\x03 \x01(\t\x12+\n\x06policy\x18\x04 \x03(\x0b\x32\x1b.PGN.Annotation.PolicyEntry\x1a-\n\x0bPolicyEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x1a\x39\n\x04Step\x12\x0c\n\x04step\x18\x01 \x01(\r\x12#\n\nannotation\x18\x02 \x01(\x0b\x32\x0f.PGN.Annotation\"\x8d\x02\n\x05Match\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07players\x18\x02 \x03(\t\x12\x1e\n\x07results\x18\x04 \x01(\x0b\x32\r.Match.Result\x12\x1a\n\x05games\x18\x05 \x03(\x0b\x32\x0b.Match.Game\x1a\x1a\n\x06Result\x12\x10\n\x04wins\x18\x01 \x03(\rB\x02\x10\x01\x1a\x8e\x01\n\x04Game\x12\x13\n\x0bgold_player\x18\x01 \x01(\r\x12\x15\n\rsilver_player\x18\x02 \x01(\r\x12\x1a\n\x12gold_player_rating\x18\x04 \x01(\r\x12\x1c\n\x14silver_player_rating\x18\x05 \x01(\r\x12\r\n\x05rated\x18\x06 \x01(\x08\x12\x11\n\x03pgn\x18\x03 \x01(\x0b\x32\x04.PGNB!Z\x1fgithub.com/ajzaff/bot_zoo/protob\x06proto3')
)




_PGN_ANNOTATION_POLICYENTRY = _descriptor.Descriptor(
  name='PolicyEntry',
  full_name='PGN.Annotation.PolicyEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='PGN.Annotation.PolicyEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='PGN.Annotation.PolicyEntry.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=289,
)

_PGN_ANNOTATION = _descriptor.Descriptor(
  name='Annotation',
  full_name='PGN.Annotation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='step', full_name='PGN.Annotation.step', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comment', full_name='PGN.Annotation.comment', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='policy', full_name='PGN.Annotation.policy', index=2,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PGN_ANNOTATION_POLICYENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=289,
)

_PGN_STEP = _descriptor.Descriptor(
  name='Step',
  full_name='PGN.Step',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='step', full_name='PGN.Step.step', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='annotation', full_name='PGN.Step.annotation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=348,
)

_PGN = _descriptor.Descriptor(
  name='PGN',
  full_name='PGN',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gold_player', full_name='PGN.gold_player', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='silver_player', full_name='PGN.silver_player', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pgn', full_name='PGN.pgn', index=2,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='steps', full_name='PGN.steps', index=3,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='annotations', full_name='PGN.annotations', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='PGN.result', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PGN_ANNOTATION, _PGN_STEP, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=348,
)


_MATCH_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='Match.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wins', full_name='Match.Result.wins', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=449,
  serialized_end=475,
)

_MATCH_GAME = _descriptor.Descriptor(
  name='Game',
  full_name='Match.Game',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gold_player', full_name='Match.Game.gold_player', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='silver_player', full_name='Match.Game.silver_player', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gold_player_rating', full_name='Match.Game.gold_player_rating', index=2,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='silver_player_rating', full_name='Match.Game.silver_player_rating', index=3,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rated', full_name='Match.Game.rated', index=4,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pgn', full_name='Match.Game.pgn', index=5,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=478,
  serialized_end=620,
)

_MATCH = _descriptor.Descriptor(
  name='Match',
  full_name='Match',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Match.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='players', full_name='Match.players', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='results', full_name='Match.results', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='games', full_name='Match.games', index=3,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MATCH_RESULT, _MATCH_GAME, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=620,
)

_PGN_ANNOTATION_POLICYENTRY.containing_type = _PGN_ANNOTATION
_PGN_ANNOTATION.fields_by_name['policy'].message_type = _PGN_ANNOTATION_POLICYENTRY
_PGN_ANNOTATION.containing_type = _PGN
_PGN_STEP.fields_by_name['annotation'].message_type = _PGN_ANNOTATION
_PGN_STEP.containing_type = _PGN
_PGN.fields_by_name['annotations'].message_type = _PGN_ANNOTATION
_MATCH_RESULT.containing_type = _MATCH
_MATCH_GAME.fields_by_name['pgn'].message_type = _PGN
_MATCH_GAME.containing_type = _MATCH
_MATCH.fields_by_name['results'].message_type = _MATCH_RESULT
_MATCH.fields_by_name['games'].message_type = _MATCH_GAME
DESCRIPTOR.message_types_by_name['PGN'] = _PGN
DESCRIPTOR.message_types_by_name['Match'] = _MATCH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PGN = _reflection.GeneratedProtocolMessageType('PGN', (_message.Message,), dict(

  Annotation = _reflection.GeneratedProtocolMessageType('Annotation', (_message.Message,), dict(

    PolicyEntry = _reflection.GeneratedProtocolMessageType('PolicyEntry', (_message.Message,), dict(
      DESCRIPTOR = _PGN_ANNOTATION_POLICYENTRY,
      __module__ = 'match_pb2'
      # @@protoc_insertion_point(class_scope:PGN.Annotation.PolicyEntry)
      ))
    ,
    DESCRIPTOR = _PGN_ANNOTATION,
    __module__ = 'match_pb2'
    # @@protoc_insertion_point(class_scope:PGN.Annotation)
    ))
  ,

  Step = _reflection.GeneratedProtocolMessageType('Step', (_message.Message,), dict(
    DESCRIPTOR = _PGN_STEP,
    __module__ = 'match_pb2'
    # @@protoc_insertion_point(class_scope:PGN.Step)
    ))
  ,
  DESCRIPTOR = _PGN,
  __module__ = 'match_pb2'
  # @@protoc_insertion_point(class_scope:PGN)
  ))
_sym_db.RegisterMessage(PGN)
_sym_db.RegisterMessage(PGN.Annotation)
_sym_db.RegisterMessage(PGN.Annotation.PolicyEntry)
_sym_db.RegisterMessage(PGN.Step)

Match = _reflection.GeneratedProtocolMessageType('Match', (_message.Message,), dict(

  Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
    DESCRIPTOR = _MATCH_RESULT,
    __module__ = 'match_pb2'
    # @@protoc_insertion_point(class_scope:Match.Result)
    ))
  ,

  Game = _reflection.GeneratedProtocolMessageType('Game', (_message.Message,), dict(
    DESCRIPTOR = _MATCH_GAME,
    __module__ = 'match_pb2'
    # @@protoc_insertion_point(class_scope:Match.Game)
    ))
  ,
  DESCRIPTOR = _MATCH,
  __module__ = 'match_pb2'
  # @@protoc_insertion_point(class_scope:Match)
  ))
_sym_db.RegisterMessage(Match)
_sym_db.RegisterMessage(Match.Result)
_sym_db.RegisterMessage(Match.Game)


DESCRIPTOR._options = None
_PGN_ANNOTATION_POLICYENTRY._options = None
_PGN.fields_by_name['steps']._options = None
_MATCH_RESULT.fields_by_name['wins']._options = None
# @@protoc_insertion_point(module_scope)
